name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      webserver:
        image: nginx:latest
        ports:
          - 8080:80
        volumes:
          - ${PWD}/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
          - ${PWD}/:/var/www/html

      php74:
        image: php:7.4
        ports:
          - 9003:9003
        volumes:
          - ${PWD}:/var/www/html
          - ${PWD}/docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
          - ${PWD}/docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP and Nginx
        run: docker-compose up -d webserver

      - name: Install dependencies
        run: docker-compose run --rm php74 composer install

      - name: Run PHPUnit tests
        run: docker-compose run --rm php74 vendor/bin/phpunit

      - name: Clean up
        run: docker-compose down
